version: "3"
services:
  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=university
    networks:
      - net
  university:
    image: university
    ports:
      - "8888:8888"
    depends_on:
      - db
      - redis
    networks:
      - net
  redis:
    container_name: redis
    image: bitnami/redis
    environment:
      - REDIS_PASSWORD=1234
    ports:
      - "6380:6379"
    networks:
      - net
networks:
  net:
    driver: bridge